### ISSUE TITLE
3d Models

### ISSUE THREAD

**Issue by ruyanve** [ruyanve/Derivation#7]
So I was wondering... how about adding a couple 3d Models? Some texture packs like Lithosare adding them for simple stuff like mushrooms. ladders and rails. It should be really simple to get these working since they are all based on json files as well.

Opinions?

**Comment by AmonFlorian** [comment]
Would put it at the end of a "To-Do" list as most important work has to be done texture-wise first. If it's necessary though to get that last bit out of a texture it would come by itself anyways.

**Comment by ruyanve** [comment]
done

**Comment by ruyanve** [comment]
Leaving this here for future reference
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2146545-opls-model-creator-free-3d-model-editor

**Comment by ruyanve** [comment]
Or maybe Sphax gives us a free version of his editor? It's not like we didn't earn it! ;-)
https://cubik.studio
